title = "mono/plain; a11y=true"
description = "An accessible, monospace plain Zola Theme"

# The URL the site will be built for
base_url = "https://exiguus.github.io/zola-monoplain"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
default_language = "en"

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
    { name = "tags", lang = "en", rss = true },
    {name = "categories", paginate_by = 5},  # 5 items per page for a term
    {name = "authors"}, # Basic definition: no feed or pagination
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ir-white"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]

keywords = "zola, theme, ink, hugo-ink"

search_enabled = true


image_resizing_disabled = false
image_format = "webp"           # "auto", "jpg", "png", "webp"

# responsive image shortcode 
# example: {{ image(src="foo.jpeg", alt="some image") }}
image_quality = 80
images_default_size = 256
images_sizes = [256, 384, 512, 576, 640, 768, 1024, 1152]

thumbnail_quality = 70
thumbnail_default_size = 128
thumbnail_sizes = [128, 256]


link_github_username = "exiguus/zola-monospace"
# link_twitter_username = ""
link_mastodon_url = "https://toot.community/@exiguus"

menu_links = [
    { url = "$BASE_URL/", name = "Home" },
    { url = "$BASE_URL/posts/", name = "Posts" },
    { url = "$BASE_URL/gallery/", name = "Gallery" },
    { url = "$BASE_URL/tags/", name = "Tags" },
    { url = "$BASE_URL/search/", name = "Search" },
]
