name: A11y Test
description: |
  This workflow runs accessibility tests using Pa11y.
  It installs dependencies, sets up the environment, and runs the tests.
  After the test it uploads the report as an artifact.

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: pnpm install && pnpm test:setup

    - name: Test Run
      shell: bash
      run: cd themes/zola-monoplain && node ./scripts/pa11y.cjs ${{ inputs.url }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: a11y-report
        path: themes/zola-monoplain/pa11y-report/**
        if-no-files-found: error
        retention-days: 7
