import json

with open('emojis.json', 'r') as file:
    emojis = json.load(file)

markdown = '''
+++
title = "Emojis"
description = "Emoji by example"
date = 2024-06-07
authors = ["Simon Gattner"]
[taxonomies]
tags= ["Zola", "Theme", "Markdown", "Emojis"]
+++

## Introduction

Zola supports emojis out of the box. You can use emojis in your markdown files like you would use them in any other text file. Just type the emoji you want to use and Zola will render it for you.

Or use the the github emoji syntax `:smile:` to render the emoji 😄.

## Configuration

```toml
[markdown]
render_emoji = true
```

should be set in your `config.toml` file.

## Implementation

Zola use the `gh-emoji` crate to render the emojis (<https://github.com/github/gemoji>). You can find a list of all supported emojis [here](https://github.com/github/gemoji/blob/master/db/emoji.json).

## Emojis

'''

for emoji in emojis:
    title = f"{emoji.get('emoji')} {emoji.get('description')}"
    json_string = json.dumps(emoji,indent=4)
    json_comment = "\n".join([f"# {line}" for line in json_string.split('\n')])
    aliases = "\n".join([f":{alias}: `:{alias}:`\n" for alias in emoji.get('aliases')])
    markdown += f"{{{{ markdown(title=\"{title}\" type=\"markdown\", code='\n<!--\n# {title}\n#\n{json_comment}\n-->\n{aliases}') }}}}\n"


markdown += '''

## Generated

This Markdown file was generated by [`emoji.py`](../emojis.py). It use [`emojis.json`](../emojis.json) to extract the list of available smilies.

'''

with open('emojis.md', 'w') as file:
    file.write(markdown)

print("Extracted a list of all emojis from `emojis.json` and save a post in `emoji.md`.")
