from pathlib import Path

# Path to the icons directory
icons_dir = Path('../../static/images/icons/')

# Get all SVG files from the icons directory
svg_files = list(icons_dir.glob('*.svg'))

# Extract icon names from filenames (without .svg extension)
# and sort them alphabetically
icon_names = sorted([f.stem for f in svg_files])

markdown = '''
+++
title = "Icons"
description = "Icons by Example"
date = 2024-06-09
update = 2026-07-12
authors = ["Simon Gattner"]
[taxonomies]
tags= ["Zola", "Markdown", "Icons", "Tabler Icons", "SVG", "Shortcode"]
+++

## Introduction

Icons are a great way to add visual interest to your website. They can be used to represent different types of content, actions, or information. In this post, I will show you how to use icons in Zola.

## Implementation

This theme use the [Tabler Icons](https://tabler.io/) icon set. Tabler Icons is a set of over 700 free MIT-licensed high-quality SVG icons for you to use in your web projects.

To use an icon in your content, you can use the `icon` shortcode. The `icon` shortcode takes the name of the icon as an argument and renders the SVG inline.
However, if you prefer to use `<img>` tags, you can pass the `img` parameter to the `icon` shortcode. This will render the icon as an `<img>` tag instead of an inline SVG.

Here is an example of how to use the `icon` shortcode:

```md
{{/* icon(name="activity",size=16,img=false) */}}
```

This will render the GitHub icon. You can find a list of all available icons on the [Tabler Icons website](https://tabler.io/icons).

## Example

Here is an example of how to use the `icon` shortcode to render the GitHub icon:

{{ icon(name="activity") }} is `{{/* icon(name="activity") */}}` in a Markdown file.

This theme uses the SVG icons from the `static/images/icons/` directory. You can find the icons in the [Tabler Icons GitHub repository](https://github.com/tabler/tabler-icons).
## Icons

A list of all available icons from the icons directory:

'''

# Generate the icon list
i = 0
for icon_name in icon_names:
    i = i + 1
    markdown += f"{i}. {{{{ icon(name=\"{icon_name}\",size=16,img=true) }}}} {{{{ icon(name=\"{icon_name}\",size=32,img=true) }}}} {{{{ icon(name=\"{icon_name}\",size=48,img=true) }}}} {icon_name}\n"
markdown += '''

## Generated

This Markdown file was generated by [`icons.py`](icons.py). It scans the `static/images/icons/` directory for SVG files to generate the list of available icons.

'''

with open('icons.md', 'w') as file:
    file.write(markdown)

print(f"Generated a list of {len(icon_names)} icons from the icons directory and saved to `icons.md`.")
