name: e2e
on:
  workflow_dispatch: # Allows manual triggering

jobs:
  a11y:
    name: A11y
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Common Setup
        uses: ./.github/actions/common-setup

      - name: A11 Test
        uses: ./.github/actions/a11y
        env:
          A11Y_URL: https://exiguus.github.io/zola-monoplain/
