name: Lighthouse
on:
  workflow_run:
    workflows: ["Github Pages"]
    types:
      - completed

jobs:
  test_run:
    name: Test run
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit URLs and validate Budget
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: https://exiguus.github.io/zola-monoplain/
          budgetPath: ./budget.json
          uploadArtifacts: true
          runs: 3
