name: perf
on:
  workflow_dispatch: # Allows manual triggering

jobs:
  lighthouse:
    name: Perf
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          node-version-file: package.json

      - name: Audit URLs and validate Budget
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: https://exiguus.github.io/zola-monoplain/
          budgetPath: ./budget.json
          uploadArtifacts: true
          runs: 3
