name: perf
on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

jobs:
  lighthouse:
    name: Test run
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: always()

    steps:
      - uses: actions/checkout@v4

      - name: Audit URLs and validate Budget
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: https://exiguus.github.io/zola-monoplain/
          budgetPath: ./budget.json
          uploadArtifacts: true
          runs: 3
