# .github/workflows/prod.yml
name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18.0

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./themes/zola-monoplain/public
          branch: gh-pages
          clean-exclude: pr-preview
          force: false

  lighthouse:
    name: Perf Prod
    needs: deploy-prod
    if: always()
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          node-version-file: package.json

      - name: Audit URLs and validate Budget
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: https://exiguus.github.io/zola-monoplain/
          budgetPath: ./budget.json
          uploadArtifacts: true
          runs: 3

  a11y:
    name: A11y Prod
    needs: deploy-prod
    if: always()
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          node-version-file: package.json

      - name: A11 Test
        uses: ./.github/actions/a11y
        with:
          url: https://exiguus.github.io/zola-monoplain/
